SUPER_CONFIG_PATH: ./configs/default.yaml

AUG_RESIZE_SCALES: [512]
AUG_MAX_SIZE: 512
AUG_RANDOM_RESIZE: [512]

BACKBONE_TYPE: video
SIGLIP_BACKBONE_TYPE: soccer_master
TEMPORAL_START_LAYER: 16
DETECTION_DATA_TYPE: video
CKPT_PATH: ./pretrained_models/google/siglip2-large-patch16-512
TEXT_ENCODER_CKPT_PATH: ./pretrained_models/google/siglip2-large-patch16-512
FREEZE_TEXT_ENCODER: True
LR_WARMUP_EPOCHS: 1
BACKBONE_HIDDEN_DIM: 1024
EPOCHS: 20
SCHEDULER_TYPE: CosineAnnealingLR

LINES_HEAD_TYPE: default

WEIGHT_DECAY: 1.0e-4
LR_BACKBONE: 5.0e-5
LR_BACKBONE_TEMPORAL: 1.0e-4
LR_TEXT_ENCODER: 5.0e-5
LR_SOCCERNET_GSR_DETECTION: 1.0e-4
LR_LINES_DETECTION: 1.0e-3
LR_KEYPOINTS_DETECTION: 1.0e-4
LR_CAMERA_REGRESSION: 1.0e-4
LR_VIDEO_CAPTION: 1.0e-4
LR_CAPTION_CLASSIFICATION: 1.0e-4
LR_CAPTION_CLASSIFICATION_CLASSIFIER: 2.0e-4
EXCLUDE_TEMPORAL_EMBEDDING_WEIGHT_DECAY: True
BACKBONE_USE_TEMPORAL_GATE: True

SAVE_CHECKPOINT_PER_EPOCH: 1

BATCH_SIZE: 1
NUM_WORKERS: 8
VIDEO_CAPTION_BATCH_SIZE: 2
VIDEO_CAPTION_TEST_BATCH_SIZE: 3
VIDEO_CAPTION_NUM_WORKERS: 16
NUM_FRAMES: 30
DATASETS_TO_HEADS:
  SoccerNetGSR_Detection: [SoccerNetGSR_Detection, LinesDetection, KeypointsDetection]
  VideoCaption: [VideoCaption, CaptionClassification]

VIDEO_CAPTION_SIGLIP_LOSS_WEIGHT: 4.0
VIDEO_CAPTION_DATASETS: ['SoccerReplay-1988', 'MatchTime', 'SoccerNet-v2']

CAPTION_CLASSIFICATION_LOSS_WEIGHT: 1.0

AUG_ENABLE_TRAINING_AUGMENTATION: True

USE_SOCCER_FACTORY_DATA: True
SOCCER_FACTORY_DATA_DIR: ./datasets/SoccerNetGS/extracted_info
SOCCER_FACTORY_DATA_IMAGE_DIR: ./datasets/SoccerNetGS/sn500
SOCCER_FACTORY_DATA_ONLY: False
USE_SOCCER_FACTORY_DATA_AMOUNT: 7000

RESUME_TRAINING: False